name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Adjust the branch as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust this to match your Java version

      # Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build the project with Gradle
      - name: Build Spring Project
        run: ./gradlew clean build -x test

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image with specific tag
      - name: Build Docker Image
        run: docker build -t ivancicka652/escheduler:latest_backend .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ivancicka652/escheduler:latest_backend
